version: '3.8'

services:
  flask_app:
    image: ghcr.io/defnone/quickfeeds:latest
    ports:
      - "8000:8000"
    volumes:
      - quickfeeds_data:/data
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8000
      LOG_LEVEL: INFO

volumes:
  quickfeeds_data: