"""add models for daily feature

Revision ID: 3dde472067d6
Revises: 115d3c7b5769
Create Date: 2024-07-28 16:30:53.610702

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3dde472067d6"
down_revision = "115d3c7b5769"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summarized_article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("image_link", sa.String(), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link"),
    )
    op.create_table(
        "article_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_article_id", sa.Integer(), nullable=False),
        sa.Column("summarized_article_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["original_article_id"],
            ["feed_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["summarized_article_id"],
            ["summarized_article.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "daily_enabled",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("openai_api_key", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "daily_active",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "daily_hours_summary",
                sa.Integer(),
                nullable=False,
                server_default="24",
            )
        )
        batch_op.add_column(
            sa.Column(
                "daily_translate",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "daily_last_sync_time_duration", sa.Integer(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "daily_process_read",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "daily_title_provider",
                sa.String(length=50),
                nullable=False,
                server_default="groq",
            )
        )
        batch_op.add_column(
            sa.Column(
                "daily_compare_titles",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("daily_sync_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("daily_sync_at")

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("daily_compare_titles")
        batch_op.drop_column("daily_title_provider")
        batch_op.drop_column("daily_process_read")
        batch_op.drop_column("daily_last_sync_time_duration")
        batch_op.drop_column("daily_translate")
        batch_op.drop_column("daily_hours_summary")
        batch_op.drop_column("daily_active")
        batch_op.drop_column("openai_api_key")

    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("daily_enabled")

    op.drop_table("article_link")
    op.drop_table("summarized_article")
    # ### end Alembic commands ###
