"""add clean_interval in Settings model

Revision ID: 890c349bf7d2
Revises: f09063ccaa9c
Create Date: 2024-06-13 19:44:32.012751

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "890c349bf7d2"
down_revision = "f09063ccaa9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "clean_interval",
                sa.Integer(),
                nullable=False,
                server_default="30",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("clean_interval")

    # ### end Alembic commands ###
