"""Added index to read field

Revision ID: ae584b9494de
Revises: 890c349bf7d2
Create Date: 2024-06-13 19:49:35.412793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae584b9494de'
down_revision = '890c349bf7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_item', schema=None) as batch_op:
        batch_op.create_index('index_feed_item_read', ['read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_item', schema=None) as batch_op:
        batch_op.drop_index('index_feed_item_read')

    # ### end Alembic commands ###
