"""add pub_date for SummarizedArticle

Revision ID: da27a96358eb
Revises: 3dde472067d6
Create Date: 2024-08-08 09:39:52.033492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da27a96358eb'
down_revision = '3dde472067d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summarized_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pub_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summarized_article', schema=None) as batch_op:
        batch_op.drop_column('pub_date')

    # ### end Alembic commands ###
