"""Initial migration.

Revision ID: f09063ccaa9c
Revises: 
Create Date: 2024-06-03 14:09:22.763670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09063ccaa9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_category_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('index_category_user_id', ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_interval', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.Column('groq_api_key', sa.String(length=100), nullable=True),
    sa.Column('translate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.create_index('index_feed_category_id', ['category_id'], unique=False)
        batch_op.create_index('index_feed_user_id', ['user_id'], unique=False)

    op.create_table('feed_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.String(length=200), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('favourite', sa.Boolean(), nullable=False),
    sa.Column('guid', sa.String(length=500), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    with op.batch_alter_table('feed_item', schema=None) as batch_op:
        batch_op.create_index('index_feed_item_feed_id', ['feed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_item_pub_date'), ['pub_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_item_pub_date'))
        batch_op.drop_index('index_feed_item_feed_id')

    op.drop_table('feed_item')
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_index('index_feed_user_id')
        batch_op.drop_index('index_feed_category_id')

    op.drop_table('feed')
    op.drop_table('settings')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('index_category_user_id')

    op.drop_table('category')
    op.drop_table('user')
    # ### end Alembic commands ###
